repos:
  # Black
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-PyYAML"]
  ## JS ##
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: ['--config', 'frontend/.prettierrc', '--ignore-unknown', '--write', '--check']
        language: node
        entry: frontend/node_modules/.bin/prettier
        require_serial: true
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|svelte)$
        additional_dependencies:
          - prettier@2.8.8
          - prettier-plugin-svelte@2.10.1
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
        name: eslint
        language: node
        entry: frontend/node_modules/eslint/bin/eslint.js
        #args: ['--fix'] #lets wait before using this
        require_serial: true
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - svelte-eslint-parser
  - repo: local
    hooks:
      - id: svelte-check
        name: Svelte check
        language: system
        entry: npx svelte-check --fail-on-warnings
        always_run: true
        pass_filenames: false
        require_serial: true
