repos:
  # Black
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-PyYAML"]
