import { writable } from 'svelte/store';
import type { CategoriesInfo, Store, CategoryRanks, CollectionRanks } from './types';

export const homeCollectionSelection = writable('new_monthly');
export const homeStoreSelection = writable('google');
export const homeCategorySelection = writable<string>('overall');

export const idStoreSelection = writable(1);
export const idCollectionSelection = writable(1);
export const idCategorySelection = writable(1);

export const homeCategoryMap = writable<CategoriesInfo>({ appCats: { categories: {} } });

const myStoreRankingsMap = {
	stores_rankings: [
		{
			store_id: 1,
			store_name: 'Google',
			collections: [
				{
					collection_id: 1,
					collection_name: 'TOP_FREE',
					categories: [
						{ category_id: 15, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 1, category_name: 'APPLICATION' },
						{ category_id: 18, category_name: 'LIBRARIES_AND_DEMO' },
						{ category_id: 24, category_name: 'PARENTING' },
						{ category_id: 3, category_name: 'ART_AND_DESIGN' },
						{ category_id: 33, category_name: 'VIDEO_PLAYERS' },
						{ category_id: 35, category_name: 'WEATHER' },
						{ category_id: 11, category_name: 'EDUCATION' },
						{ category_id: 21, category_name: 'MEDICAL' },
						{ category_id: 28, category_name: 'SHOPPING' },
						{ category_id: 30, category_name: 'SPORTS' },
						{ category_id: 16, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 34, category_name: 'WATCH_FACE' },
						{ category_id: 26, category_name: 'PHOTOGRAPHY' },
						{ category_id: 51, category_name: 'GAME_STRATEGY' },
						{ category_id: 22, category_name: 'MUSIC_AND_AUDIO' },
						{ category_id: 53, category_name: 'GAME_WORD' },
						{ category_id: 2, category_name: 'ANDROID_WEAR' },
						{ category_id: 43, category_name: 'GAME_CASUAL' },
						{ category_id: 44, category_name: 'GAME_EDUCATIONAL' },
						{ category_id: 4, category_name: 'AUTO_AND_VEHICLES' },
						{ category_id: 13, category_name: 'EVENTS' },
						{ category_id: 39, category_name: 'GAME_ARCADE' },
						{ category_id: 6, category_name: 'BOOKS_AND_REFERENCE' },
						{ category_id: 47, category_name: 'GAME_RACING' },
						{ category_id: 31, category_name: 'TOOLS' },
						{ category_id: 49, category_name: 'GAME_SIMULATION' },
						{ category_id: 19, category_name: 'LIFESTYLE' },
						{ category_id: 9, category_name: 'COMMUNICATION' },
						{ category_id: 23, category_name: 'NEWS_AND_MAGAZINES' },
						{ category_id: 14, category_name: 'FINANCE' },
						{ category_id: 50, category_name: 'GAME_SPORTS' },
						{ category_id: 37, category_name: 'GAME_ACTION' },
						{ category_id: 52, category_name: 'GAME_TRIVIA' },
						{ category_id: 29, category_name: 'SOCIAL' },
						{ category_id: 40, category_name: 'GAME_BOARD' },
						{ category_id: 5, category_name: 'BEAUTY' },
						{ category_id: 10, category_name: 'DATING' },
						{ category_id: 25, category_name: 'PERSONALIZATION' },
						{ category_id: 8, category_name: 'COMICS' },
						{ category_id: 20, category_name: 'MAPS_AND_NAVIGATION' },
						{ category_id: 36, category_name: 'GAME' },
						{ category_id: 48, category_name: 'GAME_ROLE_PLAYING' },
						{ category_id: 12, category_name: 'ENTERTAINMENT' },
						{ category_id: 54, category_name: 'FAMILY' },
						{ category_id: 32, category_name: 'TRAVEL_AND_LOCAL' },
						{ category_id: 27, category_name: 'PRODUCTIVITY' },
						{ category_id: 45, category_name: 'GAME_MUSIC' },
						{ category_id: 17, category_name: 'HOUSE_AND_HOME' },
						{ category_id: 38, category_name: 'GAME_ADVENTURE' },
						{ category_id: 41, category_name: 'GAME_CARD' },
						{ category_id: 46, category_name: 'GAME_PUZZLE' },
						{ category_id: 42, category_name: 'GAME_CASINO' },
						{ category_id: 7, category_name: 'BUSINESS' }
					]
				},
				{
					collection_id: 2,
					collection_name: 'TOP_PAID',
					categories: [
						{ category_id: 1, category_name: 'APPLICATION' },
						{ category_id: 47, category_name: 'GAME_RACING' },
						{ category_id: 37, category_name: 'GAME_ACTION' },
						{ category_id: 45, category_name: 'GAME_MUSIC' },
						{ category_id: 22, category_name: 'MUSIC_AND_AUDIO' },
						{ category_id: 28, category_name: 'SHOPPING' },
						{ category_id: 16, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 14, category_name: 'FINANCE' },
						{ category_id: 25, category_name: 'PERSONALIZATION' },
						{ category_id: 52, category_name: 'GAME_TRIVIA' },
						{ category_id: 42, category_name: 'GAME_CASINO' },
						{ category_id: 9, category_name: 'COMMUNICATION' },
						{ category_id: 35, category_name: 'WEATHER' },
						{ category_id: 36, category_name: 'GAME' },
						{ category_id: 7, category_name: 'BUSINESS' },
						{ category_id: 17, category_name: 'HOUSE_AND_HOME' },
						{ category_id: 49, category_name: 'GAME_SIMULATION' },
						{ category_id: 26, category_name: 'PHOTOGRAPHY' },
						{ category_id: 20, category_name: 'MAPS_AND_NAVIGATION' },
						{ category_id: 15, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 29, category_name: 'SOCIAL' },
						{ category_id: 32, category_name: 'TRAVEL_AND_LOCAL' },
						{ category_id: 23, category_name: 'NEWS_AND_MAGAZINES' },
						{ category_id: 48, category_name: 'GAME_ROLE_PLAYING' },
						{ category_id: 2, category_name: 'ANDROID_WEAR' },
						{ category_id: 31, category_name: 'TOOLS' },
						{ category_id: 11, category_name: 'EDUCATION' },
						{ category_id: 39, category_name: 'GAME_ARCADE' },
						{ category_id: 8, category_name: 'COMICS' },
						{ category_id: 27, category_name: 'PRODUCTIVITY' },
						{ category_id: 38, category_name: 'GAME_ADVENTURE' },
						{ category_id: 6, category_name: 'BOOKS_AND_REFERENCE' },
						{ category_id: 30, category_name: 'SPORTS' },
						{ category_id: 18, category_name: 'LIBRARIES_AND_DEMO' },
						{ category_id: 33, category_name: 'VIDEO_PLAYERS' },
						{ category_id: 46, category_name: 'GAME_PUZZLE' },
						{ category_id: 12, category_name: 'ENTERTAINMENT' },
						{ category_id: 4, category_name: 'AUTO_AND_VEHICLES' },
						{ category_id: 24, category_name: 'PARENTING' },
						{ category_id: 51, category_name: 'GAME_STRATEGY' },
						{ category_id: 21, category_name: 'MEDICAL' },
						{ category_id: 5, category_name: 'BEAUTY' },
						{ category_id: 44, category_name: 'GAME_EDUCATIONAL' },
						{ category_id: 54, category_name: 'FAMILY' },
						{ category_id: 43, category_name: 'GAME_CASUAL' },
						{ category_id: 40, category_name: 'GAME_BOARD' },
						{ category_id: 41, category_name: 'GAME_CARD' },
						{ category_id: 3, category_name: 'ART_AND_DESIGN' },
						{ category_id: 19, category_name: 'LIFESTYLE' },
						{ category_id: 50, category_name: 'GAME_SPORTS' },
						{ category_id: 53, category_name: 'GAME_WORD' },
						{ category_id: 34, category_name: 'WATCH_FACE' }
					]
				},
				{
					collection_id: 3,
					collection_name: 'GROSSING',
					categories: [
						{ category_id: 42, category_name: 'GAME_CASINO' },
						{ category_id: 24, category_name: 'PARENTING' },
						{ category_id: 13, category_name: 'EVENTS' },
						{ category_id: 26, category_name: 'PHOTOGRAPHY' },
						{ category_id: 43, category_name: 'GAME_CASUAL' },
						{ category_id: 50, category_name: 'GAME_SPORTS' },
						{ category_id: 19, category_name: 'LIFESTYLE' },
						{ category_id: 38, category_name: 'GAME_ADVENTURE' },
						{ category_id: 20, category_name: 'MAPS_AND_NAVIGATION' },
						{ category_id: 21, category_name: 'MEDICAL' },
						{ category_id: 15, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 22, category_name: 'MUSIC_AND_AUDIO' },
						{ category_id: 46, category_name: 'GAME_PUZZLE' },
						{ category_id: 4, category_name: 'AUTO_AND_VEHICLES' },
						{ category_id: 14, category_name: 'FINANCE' },
						{ category_id: 33, category_name: 'VIDEO_PLAYERS' },
						{ category_id: 9, category_name: 'COMMUNICATION' },
						{ category_id: 27, category_name: 'PRODUCTIVITY' },
						{ category_id: 36, category_name: 'GAME' },
						{ category_id: 8, category_name: 'COMICS' },
						{ category_id: 25, category_name: 'PERSONALIZATION' },
						{ category_id: 3, category_name: 'ART_AND_DESIGN' },
						{ category_id: 34, category_name: 'WATCH_FACE' },
						{ category_id: 31, category_name: 'TOOLS' },
						{ category_id: 40, category_name: 'GAME_BOARD' },
						{ category_id: 32, category_name: 'TRAVEL_AND_LOCAL' },
						{ category_id: 52, category_name: 'GAME_TRIVIA' },
						{ category_id: 10, category_name: 'DATING' },
						{ category_id: 47, category_name: 'GAME_RACING' },
						{ category_id: 45, category_name: 'GAME_MUSIC' },
						{ category_id: 29, category_name: 'SOCIAL' },
						{ category_id: 1, category_name: 'APPLICATION' },
						{ category_id: 54, category_name: 'FAMILY' },
						{ category_id: 30, category_name: 'SPORTS' },
						{ category_id: 35, category_name: 'WEATHER' },
						{ category_id: 37, category_name: 'GAME_ACTION' },
						{ category_id: 49, category_name: 'GAME_SIMULATION' },
						{ category_id: 6, category_name: 'BOOKS_AND_REFERENCE' },
						{ category_id: 5, category_name: 'BEAUTY' },
						{ category_id: 2, category_name: 'ANDROID_WEAR' },
						{ category_id: 28, category_name: 'SHOPPING' },
						{ category_id: 7, category_name: 'BUSINESS' },
						{ category_id: 16, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 41, category_name: 'GAME_CARD' },
						{ category_id: 48, category_name: 'GAME_ROLE_PLAYING' },
						{ category_id: 18, category_name: 'LIBRARIES_AND_DEMO' },
						{ category_id: 39, category_name: 'GAME_ARCADE' },
						{ category_id: 23, category_name: 'NEWS_AND_MAGAZINES' },
						{ category_id: 17, category_name: 'HOUSE_AND_HOME' },
						{ category_id: 51, category_name: 'GAME_STRATEGY' },
						{ category_id: 12, category_name: 'ENTERTAINMENT' },
						{ category_id: 44, category_name: 'GAME_EDUCATIONAL' },
						{ category_id: 53, category_name: 'GAME_WORD' },
						{ category_id: 11, category_name: 'EDUCATION' }
					]
				}
			]
		},
		{
			store_id: 2,
			store_name: 'Apple',
			collections: [
				{
					collection_id: 4,
					collection_name: 'TOP_FREE_IOS',
					categories: [
						{ category_id: 121, category_name: 'SPORTS' },
						{ category_id: 62, category_name: 'GAMES' },
						{ category_id: 82, category_name: 'LIFESTYLE' },
						{ category_id: 101, category_name: 'MAGAZINES_POLITICS' },
						{ category_id: 77, category_name: 'GAMES_SPORTS' },
						{ category_id: 118, category_name: 'REFERENCE' },
						{ category_id: 75, category_name: 'GAMES_ROLE_PLAYING' },
						{ category_id: 112, category_name: 'MEDICAL' },
						{ category_id: 59, category_name: 'ENTERTAINMENT' },
						{ category_id: 114, category_name: 'NAVIGATION' },
						{ category_id: 74, category_name: 'GAMES_RACING' },
						{ category_id: 123, category_name: 'UTILITIES' },
						{ category_id: 124, category_name: 'WEATHER' },
						{ category_id: 64, category_name: 'GAMES_ADVENTURE' },
						{ category_id: 76, category_name: 'GAMES_SIMULATION' },
						{ category_id: 78, category_name: 'GAMES_STRATEGY' },
						{ category_id: 80, category_name: 'GAMES_WORD' },
						{ category_id: 117, category_name: 'PRODUCTIVITY' },
						{ category_id: 119, category_name: 'SHOPPING' },
						{ category_id: 68, category_name: 'GAMES_CASINO' },
						{ category_id: 81, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 79, category_name: 'GAMES_TRIVIA' },
						{ category_id: 55, category_name: 'BOOKS' },
						{ category_id: 113, category_name: 'MUSIC' },
						{ category_id: 120, category_name: 'SOCIAL_NETWORKING' },
						{ category_id: 63, category_name: 'GAMES_ACTION' },
						{ category_id: 122, category_name: 'TRAVEL' },
						{ category_id: 116, category_name: 'PHOTO_AND_VIDEO' },
						{ category_id: 72, category_name: 'GAMES_MUSIC' },
						{ category_id: 67, category_name: 'GAMES_CARD' },
						{ category_id: 60, category_name: 'FINANCE' },
						{ category_id: 73, category_name: 'GAMES_PUZZLE' },
						{ category_id: 58, category_name: 'EDUCATION' },
						{ category_id: 65, category_name: 'GAMES_ARCADE' },
						{ category_id: 83, category_name: 'MAGAZINES_AND_NEWSPAPERS' },
						{ category_id: 66, category_name: 'GAMES_BOARD' },
						{ category_id: 71, category_name: 'GAMES_FAMILY' },
						{ category_id: 61, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 56, category_name: 'BUSINESS' },
						{ category_id: 115, category_name: 'NEWS' }
					]
				},
				{
					collection_id: 5,
					collection_name: 'TOP_FREE_IPAD',
					categories: [
						{ category_id: 66, category_name: 'GAMES_BOARD' },
						{ category_id: 114, category_name: 'NAVIGATION' },
						{ category_id: 56, category_name: 'BUSINESS' },
						{ category_id: 73, category_name: 'GAMES_PUZZLE' },
						{ category_id: 118, category_name: 'REFERENCE' },
						{ category_id: 62, category_name: 'GAMES' },
						{ category_id: 112, category_name: 'MEDICAL' },
						{ category_id: 77, category_name: 'GAMES_SPORTS' },
						{ category_id: 64, category_name: 'GAMES_ADVENTURE' },
						{ category_id: 122, category_name: 'TRAVEL' },
						{ category_id: 120, category_name: 'SOCIAL_NETWORKING' },
						{ category_id: 124, category_name: 'WEATHER' },
						{ category_id: 79, category_name: 'GAMES_TRIVIA' },
						{ category_id: 67, category_name: 'GAMES_CARD' },
						{ category_id: 58, category_name: 'EDUCATION' },
						{ category_id: 65, category_name: 'GAMES_ARCADE' },
						{ category_id: 74, category_name: 'GAMES_RACING' },
						{ category_id: 82, category_name: 'LIFESTYLE' },
						{ category_id: 123, category_name: 'UTILITIES' },
						{ category_id: 83, category_name: 'MAGAZINES_AND_NEWSPAPERS' },
						{ category_id: 75, category_name: 'GAMES_ROLE_PLAYING' },
						{ category_id: 59, category_name: 'ENTERTAINMENT' },
						{ category_id: 116, category_name: 'PHOTO_AND_VIDEO' },
						{ category_id: 113, category_name: 'MUSIC' },
						{ category_id: 71, category_name: 'GAMES_FAMILY' },
						{ category_id: 101, category_name: 'MAGAZINES_POLITICS' },
						{ category_id: 119, category_name: 'SHOPPING' },
						{ category_id: 121, category_name: 'SPORTS' },
						{ category_id: 55, category_name: 'BOOKS' },
						{ category_id: 63, category_name: 'GAMES_ACTION' },
						{ category_id: 61, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 68, category_name: 'GAMES_CASINO' },
						{ category_id: 115, category_name: 'NEWS' },
						{ category_id: 117, category_name: 'PRODUCTIVITY' },
						{ category_id: 81, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 72, category_name: 'GAMES_MUSIC' },
						{ category_id: 78, category_name: 'GAMES_STRATEGY' },
						{ category_id: 80, category_name: 'GAMES_WORD' },
						{ category_id: 60, category_name: 'FINANCE' },
						{ category_id: 76, category_name: 'GAMES_SIMULATION' }
					]
				},
				{
					collection_id: 6,
					collection_name: 'TOP_GROSSING_IOS',
					categories: [
						{ category_id: 117, category_name: 'PRODUCTIVITY' },
						{ category_id: 116, category_name: 'PHOTO_AND_VIDEO' },
						{ category_id: 83, category_name: 'MAGAZINES_AND_NEWSPAPERS' },
						{ category_id: 115, category_name: 'NEWS' },
						{ category_id: 112, category_name: 'MEDICAL' },
						{ category_id: 68, category_name: 'GAMES_CASINO' },
						{ category_id: 70, category_name: 'GAMES_EDUCATIONAL' },
						{ category_id: 82, category_name: 'LIFESTYLE' },
						{ category_id: 66, category_name: 'GAMES_BOARD' },
						{ category_id: 123, category_name: 'UTILITIES' },
						{ category_id: 81, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 79, category_name: 'GAMES_TRIVIA' },
						{ category_id: 118, category_name: 'REFERENCE' },
						{ category_id: 57, category_name: 'CATALOGS' },
						{ category_id: 64, category_name: 'GAMES_ADVENTURE' },
						{ category_id: 63, category_name: 'GAMES_ACTION' },
						{ category_id: 67, category_name: 'GAMES_CARD' },
						{ category_id: 77, category_name: 'GAMES_SPORTS' },
						{ category_id: 76, category_name: 'GAMES_SIMULATION' },
						{ category_id: 59, category_name: 'ENTERTAINMENT' },
						{ category_id: 56, category_name: 'BUSINESS' },
						{ category_id: 65, category_name: 'GAMES_ARCADE' },
						{ category_id: 101, category_name: 'MAGAZINES_POLITICS' },
						{ category_id: 58, category_name: 'EDUCATION' },
						{ category_id: 120, category_name: 'SOCIAL_NETWORKING' },
						{ category_id: 119, category_name: 'SHOPPING' },
						{ category_id: 78, category_name: 'GAMES_STRATEGY' },
						{ category_id: 122, category_name: 'TRAVEL' },
						{ category_id: 74, category_name: 'GAMES_RACING' },
						{ category_id: 124, category_name: 'WEATHER' },
						{ category_id: 60, category_name: 'FINANCE' },
						{ category_id: 80, category_name: 'GAMES_WORD' },
						{ category_id: 113, category_name: 'MUSIC' },
						{ category_id: 62, category_name: 'GAMES' },
						{ category_id: 69, category_name: 'GAMES_DICE' },
						{ category_id: 114, category_name: 'NAVIGATION' },
						{ category_id: 73, category_name: 'GAMES_PUZZLE' },
						{ category_id: 55, category_name: 'BOOKS' },
						{ category_id: 72, category_name: 'GAMES_MUSIC' },
						{ category_id: 71, category_name: 'GAMES_FAMILY' },
						{ category_id: 75, category_name: 'GAMES_ROLE_PLAYING' },
						{ category_id: 121, category_name: 'SPORTS' },
						{ category_id: 61, category_name: 'FOOD_AND_DRINK' }
					]
				},
				{
					collection_id: 7,
					collection_name: 'TOP_GROSSING_IPAD',
					categories: [
						{ category_id: 68, category_name: 'GAMES_CASINO' },
						{ category_id: 120, category_name: 'SOCIAL_NETWORKING' },
						{ category_id: 73, category_name: 'GAMES_PUZZLE' },
						{ category_id: 122, category_name: 'TRAVEL' },
						{ category_id: 113, category_name: 'MUSIC' },
						{ category_id: 75, category_name: 'GAMES_ROLE_PLAYING' },
						{ category_id: 69, category_name: 'GAMES_DICE' },
						{ category_id: 66, category_name: 'GAMES_BOARD' },
						{ category_id: 112, category_name: 'MEDICAL' },
						{ category_id: 59, category_name: 'ENTERTAINMENT' },
						{ category_id: 56, category_name: 'BUSINESS' },
						{ category_id: 101, category_name: 'MAGAZINES_POLITICS' },
						{ category_id: 65, category_name: 'GAMES_ARCADE' },
						{ category_id: 83, category_name: 'MAGAZINES_AND_NEWSPAPERS' },
						{ category_id: 82, category_name: 'LIFESTYLE' },
						{ category_id: 81, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 118, category_name: 'REFERENCE' },
						{ category_id: 114, category_name: 'NAVIGATION' },
						{ category_id: 78, category_name: 'GAMES_STRATEGY' },
						{ category_id: 70, category_name: 'GAMES_EDUCATIONAL' },
						{ category_id: 60, category_name: 'FINANCE' },
						{ category_id: 62, category_name: 'GAMES' },
						{ category_id: 123, category_name: 'UTILITIES' },
						{ category_id: 57, category_name: 'CATALOGS' },
						{ category_id: 80, category_name: 'GAMES_WORD' },
						{ category_id: 71, category_name: 'GAMES_FAMILY' },
						{ category_id: 72, category_name: 'GAMES_MUSIC' },
						{ category_id: 117, category_name: 'PRODUCTIVITY' },
						{ category_id: 119, category_name: 'SHOPPING' },
						{ category_id: 55, category_name: 'BOOKS' },
						{ category_id: 115, category_name: 'NEWS' },
						{ category_id: 116, category_name: 'PHOTO_AND_VIDEO' },
						{ category_id: 124, category_name: 'WEATHER' },
						{ category_id: 58, category_name: 'EDUCATION' },
						{ category_id: 63, category_name: 'GAMES_ACTION' },
						{ category_id: 61, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 77, category_name: 'GAMES_SPORTS' },
						{ category_id: 79, category_name: 'GAMES_TRIVIA' },
						{ category_id: 74, category_name: 'GAMES_RACING' },
						{ category_id: 76, category_name: 'GAMES_SIMULATION' },
						{ category_id: 121, category_name: 'SPORTS' },
						{ category_id: 64, category_name: 'GAMES_ADVENTURE' },
						{ category_id: 67, category_name: 'GAMES_CARD' }
					]
				},
				{
					collection_id: 8,
					collection_name: 'TOP_PAID_IOS',
					categories: [
						{ category_id: 55, category_name: 'BOOKS' },
						{ category_id: 78, category_name: 'GAMES_STRATEGY' },
						{ category_id: 57, category_name: 'CATALOGS' },
						{ category_id: 68, category_name: 'GAMES_CASINO' },
						{ category_id: 74, category_name: 'GAMES_RACING' },
						{ category_id: 81, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 58, category_name: 'EDUCATION' },
						{ category_id: 120, category_name: 'SOCIAL_NETWORKING' },
						{ category_id: 69, category_name: 'GAMES_DICE' },
						{ category_id: 73, category_name: 'GAMES_PUZZLE' },
						{ category_id: 80, category_name: 'GAMES_WORD' },
						{ category_id: 118, category_name: 'REFERENCE' },
						{ category_id: 112, category_name: 'MEDICAL' },
						{ category_id: 63, category_name: 'GAMES_ACTION' },
						{ category_id: 59, category_name: 'ENTERTAINMENT' },
						{ category_id: 79, category_name: 'GAMES_TRIVIA' },
						{ category_id: 124, category_name: 'WEATHER' },
						{ category_id: 70, category_name: 'GAMES_EDUCATIONAL' },
						{ category_id: 77, category_name: 'GAMES_SPORTS' },
						{ category_id: 115, category_name: 'NEWS' },
						{ category_id: 72, category_name: 'GAMES_MUSIC' },
						{ category_id: 71, category_name: 'GAMES_FAMILY' },
						{ category_id: 117, category_name: 'PRODUCTIVITY' },
						{ category_id: 121, category_name: 'SPORTS' },
						{ category_id: 82, category_name: 'LIFESTYLE' },
						{ category_id: 76, category_name: 'GAMES_SIMULATION' },
						{ category_id: 123, category_name: 'UTILITIES' },
						{ category_id: 122, category_name: 'TRAVEL' },
						{ category_id: 67, category_name: 'GAMES_CARD' },
						{ category_id: 114, category_name: 'NAVIGATION' },
						{ category_id: 113, category_name: 'MUSIC' },
						{ category_id: 83, category_name: 'MAGAZINES_AND_NEWSPAPERS' },
						{ category_id: 116, category_name: 'PHOTO_AND_VIDEO' },
						{ category_id: 60, category_name: 'FINANCE' },
						{ category_id: 65, category_name: 'GAMES_ARCADE' },
						{ category_id: 66, category_name: 'GAMES_BOARD' },
						{ category_id: 119, category_name: 'SHOPPING' },
						{ category_id: 56, category_name: 'BUSINESS' },
						{ category_id: 75, category_name: 'GAMES_ROLE_PLAYING' },
						{ category_id: 64, category_name: 'GAMES_ADVENTURE' },
						{ category_id: 61, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 62, category_name: 'GAMES' }
					]
				},
				{
					collection_id: 9,
					collection_name: 'TOP_PAID_IPAD',
					categories: [
						{ category_id: 61, category_name: 'FOOD_AND_DRINK' },
						{ category_id: 66, category_name: 'GAMES_BOARD' },
						{ category_id: 112, category_name: 'MEDICAL' },
						{ category_id: 59, category_name: 'ENTERTAINMENT' },
						{ category_id: 67, category_name: 'GAMES_CARD' },
						{ category_id: 77, category_name: 'GAMES_SPORTS' },
						{ category_id: 124, category_name: 'WEATHER' },
						{ category_id: 83, category_name: 'MAGAZINES_AND_NEWSPAPERS' },
						{ category_id: 73, category_name: 'GAMES_PUZZLE' },
						{ category_id: 122, category_name: 'TRAVEL' },
						{ category_id: 64, category_name: 'GAMES_ADVENTURE' },
						{ category_id: 56, category_name: 'BUSINESS' },
						{ category_id: 72, category_name: 'GAMES_MUSIC' },
						{ category_id: 68, category_name: 'GAMES_CASINO' },
						{ category_id: 117, category_name: 'PRODUCTIVITY' },
						{ category_id: 70, category_name: 'GAMES_EDUCATIONAL' },
						{ category_id: 69, category_name: 'GAMES_DICE' },
						{ category_id: 74, category_name: 'GAMES_RACING' },
						{ category_id: 62, category_name: 'GAMES' },
						{ category_id: 55, category_name: 'BOOKS' },
						{ category_id: 118, category_name: 'REFERENCE' },
						{ category_id: 115, category_name: 'NEWS' },
						{ category_id: 116, category_name: 'PHOTO_AND_VIDEO' },
						{ category_id: 58, category_name: 'EDUCATION' },
						{ category_id: 81, category_name: 'HEALTH_AND_FITNESS' },
						{ category_id: 120, category_name: 'SOCIAL_NETWORKING' },
						{ category_id: 113, category_name: 'MUSIC' },
						{ category_id: 119, category_name: 'SHOPPING' },
						{ category_id: 114, category_name: 'NAVIGATION' },
						{ category_id: 82, category_name: 'LIFESTYLE' },
						{ category_id: 79, category_name: 'GAMES_TRIVIA' },
						{ category_id: 121, category_name: 'SPORTS' },
						{ category_id: 78, category_name: 'GAMES_STRATEGY' },
						{ category_id: 76, category_name: 'GAMES_SIMULATION' },
						{ category_id: 71, category_name: 'GAMES_FAMILY' },
						{ category_id: 65, category_name: 'GAMES_ARCADE' },
						{ category_id: 63, category_name: 'GAMES_ACTION' },
						{ category_id: 60, category_name: 'FINANCE' },
						{ category_id: 57, category_name: 'CATALOGS' },
						{ category_id: 80, category_name: 'GAMES_WORD' },
						{ category_id: 123, category_name: 'UTILITIES' },
						{ category_id: 75, category_name: 'GAMES_ROLE_PLAYING' }
					]
				}
			]
		}
	]
};

// Lookup tables with TypeScript type annotations
export const storeIDLookup: Record<number, Store> = {};
export const collectionIDLookup: Record<number, Record<number, CollectionRanks>> = {};
export const categoryIDLookup: Record<number, Record<number, CategoryRanks>> = {};

// Populate the lookup tables with type safety
myStoreRankingsMap.stores_rankings.forEach((store: Store) => {
	storeIDLookup[store.store_id] = store;

	store.collections.forEach((collection: CollectionRanks) => {
		if (!collectionIDLookup[store.store_id]) {
			collectionIDLookup[store.store_id] = {};
		}
		collectionIDLookup[store.store_id][collection.collection_id] = collection;

		collection.categories.forEach((category: CategoryRanks) => {
			if (!categoryIDLookup[collection.collection_id]) {
				categoryIDLookup[collection.collection_id] = {};
			}
			categoryIDLookup[collection.collection_id][category.category_id] = category;
		});
	});
});

export const plotColors = [
	'#636efa',
	'#EF553B',
	'#00cc96',
	'#ab63fa',
	'#FFA15A',
	'#19d3f3',
	'#FF6692',
	'#B6E880',
	'#FF97FF',
	'#FECB52',
	'#AA0DFE',
	'#3283FE',
	'#85660D',
	'#782AB6',
	'#565656',
	'#1C8356',
	'#16FF32',
	'#F7E1A0',
	'#E2E2E2',
	'#1CBE4F',
	'#C4451C',
	'#DEA0FD',
	'#FE00FA',
	'#325A9B',
	'#FEAF16',
	'#F8A19F',
	'#90AD1C',
	'#F6222E',
	'#1CFFCE',
	'#2ED9FF',
	'#B10DA1',
	'#C075A6',
	'#FC1CBF',
	'#B00068',
	'#FBE426',
	'#FA0087'
];
