name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Deploy to my EC2
        uses: appleboy/ssh-action@master
        env:
          TARGETDIR: app-store-dash
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: TARGETDIR
          script_stop: true
          script: |
            cd $TARGETDIR
            pwd
            git pull origin main
            cd frontend
            sudo systemctl enable /home/ubuntu/app-store-dash/scripts/app-store-api.service
            sudo systemctl enable /home/ubuntu/app-store-dash/scripts/app-store-api.socket
            sudo systemctl enable /home/ubuntu/app-store-dash/scripts/app-store-frontend.service
            sudo systemctl daemon-reload
            sudo systemctl restart app-store-api
            npm run build
            sudo systemctl restart app-store-frontend
